# Generated by Django 5.0.14 on 2026-01-23 20:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ANS",
            fields=[
                (
                    "id_ans",
                    models.AutoField(
                        db_column="id-ans",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID del ANS",
                    ),
                ),
                (
                    "ans_name",
                    models.CharField(
                        db_column="ans-name",
                        max_length=45,
                        verbose_name="Nombre del ANS",
                    ),
                ),
                (
                    "ans_description",
                    models.CharField(
                        blank=True,
                        db_column="ans-description",
                        max_length=100,
                        null=True,
                        verbose_name="Descripción del ANS",
                    ),
                ),
            ],
            options={
                "verbose_name": "ANS",
                "verbose_name_plural": "ANS",
                "db_table": "ans",
            },
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "client_name",
                    models.CharField(
                        db_column="client-name",
                        max_length=45,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nombre del Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "db_table": "clients",
            },
        ),
        migrations.CreateModel(
            name="ClosingCode",
            fields=[
                (
                    "id_closing_code",
                    models.AutoField(
                        db_column="id-closing-code",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID del Código de Cierre",
                    ),
                ),
                (
                    "closing_code_name",
                    models.CharField(
                        blank=True,
                        db_column="closing-code-name",
                        max_length=45,
                        null=True,
                        unique=True,
                        verbose_name="Nombre del Código de Cierre",
                    ),
                ),
                (
                    "closing_code_description",
                    models.CharField(
                        blank=True,
                        db_column="closing-code-description",
                        max_length=100,
                        null=True,
                        verbose_name="Descripción del Código de Cierre",
                    ),
                ),
            ],
            options={
                "verbose_name": "Código de Cierre",
                "verbose_name_plural": "Códigos de Cierre",
                "db_table": "closing-codes",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "rol_name",
                    models.CharField(
                        db_column="rol-name",
                        max_length=45,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nombre del Rol",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Icono"
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id_services",
                    models.AutoField(
                        db_column="id-services",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID del Servicio",
                    ),
                ),
                (
                    "service_name",
                    models.CharField(
                        blank=True,
                        db_column="service-name",
                        max_length=45,
                        null=True,
                        unique=True,
                        verbose_name="Nombre del Servicio",
                    ),
                ),
                (
                    "service_description",
                    models.CharField(
                        blank=True,
                        db_column="service-description",
                        max_length=100,
                        null=True,
                        verbose_name="Descripción del Servicio",
                    ),
                ),
                (
                    "estimated_solution_time",
                    models.TimeField(
                        blank=True,
                        db_column="estimated-solution-time",
                        null=True,
                        verbose_name="Tiempo Estimado de Solución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "db_table": "services",
            },
        ),
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id_status",
                    models.AutoField(
                        db_column="id-status",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID del Estado",
                    ),
                ),
                (
                    "status_name",
                    models.CharField(
                        db_column="status-name",
                        max_length=45,
                        verbose_name="Nombre del Estado",
                    ),
                ),
                (
                    "status_description",
                    models.CharField(
                        blank=True,
                        db_column="status-description",
                        max_length=100,
                        null=True,
                        verbose_name="Descripción del Estado",
                    ),
                ),
                (
                    "is_backlog",
                    models.BooleanField(
                        db_column="is-backlog", default=False, verbose_name="Es Backlog"
                    ),
                ),
            ],
            options={
                "verbose_name": "Estado",
                "verbose_name_plural": "Estados",
                "db_table": "status",
            },
        ),
        migrations.CreateModel(
            name="TicketPriority",
            fields=[
                (
                    "priority_name",
                    models.CharField(
                        db_column="priority-name",
                        max_length=45,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nombre de la Prioridad",
                    ),
                ),
                (
                    "priority_description",
                    models.CharField(
                        blank=True,
                        db_column="priority-description",
                        max_length=100,
                        null=True,
                        verbose_name="Descripción de la Prioridad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prioridad de Ticket",
                "verbose_name_plural": "Prioridades de Tickets",
                "db_table": "ticket-priority",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "network_user",
                    models.CharField(
                        db_column="network-user",
                        max_length=45,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Usuario de Red",
                    ),
                ),
                (
                    "mail",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Correo"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Teléfono"
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id_working_hours",
                    models.AutoField(
                        db_column="id-working-hours",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID de Horas Laborales",
                    ),
                ),
                (
                    "week_day",
                    models.CharField(
                        db_column="week-day",
                        max_length=15,
                        verbose_name="Día de la Semana",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        db_column="start-time", verbose_name="Hora de Inicio"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(db_column="end-time", verbose_name="Hora de Fin"),
                ),
            ],
            options={
                "verbose_name": "Horas Laborales",
                "verbose_name_plural": "Horas Laborales",
                "db_table": "working-hours",
            },
        ),
        migrations.CreateModel(
            name="EUser",
            fields=[
                (
                    "network_user",
                    models.CharField(
                        db_column="network-user",
                        max_length=45,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Usuario de Red",
                    ),
                ),
                ("name", models.CharField(max_length=45, verbose_name="Nombre")),
                (
                    "middle_name",
                    models.CharField(
                        blank=True,
                        db_column="middle-name",
                        max_length=45,
                        null=True,
                        verbose_name="Segundo Nombre",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        db_column="last-name",
                        max_length=45,
                        verbose_name="Apellido Paterno",
                    ),
                ),
                (
                    "second_last_name",
                    models.CharField(
                        blank=True,
                        db_column="second-last-name",
                        max_length=45,
                        null=True,
                        verbose_name="Apellido Materno",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "user_client_name",
                    models.ForeignKey(
                        db_column="user-client-name",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.client",
                        verbose_name="Cliente",
                    ),
                ),
                (
                    "rol_name",
                    models.ForeignKey(
                        db_column="rol-name",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.role",
                        verbose_name="Rol",
                    ),
                ),
                (
                    "id_services",
                    models.ForeignKey(
                        db_column="id-services",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.service",
                        verbose_name="Servicio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario Empresarial",
                "verbose_name_plural": "Usuarios Empresariales",
                "db_table": "e-users",
            },
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "program_name",
                    models.CharField(
                        db_column="program-name",
                        max_length=45,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nombre del Programa",
                    ),
                ),
                (
                    "client_name",
                    models.ForeignKey(
                        db_column="client-name",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.client",
                        verbose_name="Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Programa",
                "verbose_name_plural": "Programas",
                "db_table": "programs",
            },
        ),
        migrations.CreateModel(
            name="SubProgram",
            fields=[
                (
                    "sub_program_name",
                    models.CharField(
                        db_column="sub-program-name",
                        max_length=45,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nombre del Sub-programa",
                    ),
                ),
                (
                    "program_name",
                    models.ForeignKey(
                        db_column="program-name",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.program",
                        verbose_name="Programa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sub-programa",
                "verbose_name_plural": "Sub-programas",
                "db_table": "sub-programs",
            },
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id_ticket",
                    models.AutoField(
                        db_column="id-ticket",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID del Ticket",
                    ),
                ),
                (
                    "ticket_title",
                    models.CharField(
                        db_column="ticket-title",
                        max_length=45,
                        verbose_name="Título del Ticket",
                    ),
                ),
                (
                    "ticket_description",
                    models.CharField(
                        db_column="ticket-description",
                        max_length=250,
                        verbose_name="Descripción del Ticket",
                    ),
                ),
                (
                    "ticket_attachments",
                    models.CharField(
                        blank=True,
                        db_column="ticket-attachments",
                        max_length=250,
                        null=True,
                        verbose_name="Adjuntos del Ticket",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        db_column="create-at",
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="update-at",
                        verbose_name="Fecha de Actualización",
                    ),
                ),
                (
                    "assigned_to",
                    models.CharField(
                        blank=True,
                        db_column="assigned-to",
                        max_length=45,
                        null=True,
                        verbose_name="Asignado a",
                    ),
                ),
                (
                    "closing_date",
                    models.DateTimeField(
                        blank=True,
                        db_column="closing date",
                        null=True,
                        verbose_name="Fecha de Cierre",
                    ),
                ),
                (
                    "estimated_closing_date",
                    models.DateTimeField(
                        blank=True,
                        db_column="estimated-closing-date",
                        null=True,
                        verbose_name="Fecha Estimada de Cierre",
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        db_column="status-id",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.status",
                        verbose_name="Estado",
                    ),
                ),
                (
                    "sub_program_name",
                    models.ForeignKey(
                        db_column="sub-program-name",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.subprogram",
                        verbose_name="Sub-programa",
                    ),
                ),
                (
                    "ticket_ans",
                    models.ForeignKey(
                        db_column="ticket-ans",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.ans",
                        verbose_name="ANS",
                    ),
                ),
                (
                    "ticket_closing_code",
                    models.ForeignKey(
                        blank=True,
                        db_column="ticket--closing-code",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.closingcode",
                        verbose_name="Código de Cierre",
                    ),
                ),
                (
                    "ticket_service",
                    models.ForeignKey(
                        db_column="ticket-service",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.service",
                        verbose_name="Servicio",
                    ),
                ),
                (
                    "ticket_priority",
                    models.ForeignKey(
                        db_column="ticket-priority",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.ticketpriority",
                        verbose_name="Prioridad",
                    ),
                ),
                (
                    "reporter_user",
                    models.ForeignKey(
                        db_column="reporter-user",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.user",
                        verbose_name="Usuario Reportador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket",
                "verbose_name_plural": "Tickets",
                "db_table": "tickets",
            },
        ),
        migrations.CreateModel(
            name="ReportedTime",
            fields=[
                (
                    "id_reported_times",
                    models.AutoField(
                        db_column="id-reported-times",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID del Tiempo Reportado",
                    ),
                ),
                (
                    "date_reported",
                    models.DateTimeField(
                        db_column="date-reported", verbose_name="Fecha Reportada"
                    ),
                ),
                (
                    "reported_time",
                    models.TimeField(
                        db_column="reported-time", verbose_name="Tiempo Reportado"
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        db_column="create-at",
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="update-at",
                        verbose_name="Fecha de Actualización",
                    ),
                ),
                (
                    "network_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="network-user",
                        help_text="Usuario que reporta el tiempo",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.euser",
                        verbose_name="Usuario de Red",
                    ),
                ),
                (
                    "id_ticket",
                    models.ForeignKey(
                        db_column="id-ticket",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.ticket",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiempo Reportado",
                "verbose_name_plural": "Tiempos Reportados",
                "db_table": "reported-times",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id_note",
                    models.AutoField(
                        db_column="id-note",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID de la Nota",
                    ),
                ),
                ("note", models.TextField(verbose_name="Nota")),
                (
                    "visible_to_client",
                    models.BooleanField(
                        db_column="visible-to-client",
                        default=False,
                        verbose_name="Visible para el Cliente",
                    ),
                ),
                (
                    "create_at",
                    models.DateTimeField(
                        db_column="create-at",
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Creación",
                    ),
                ),
                (
                    "update_at",
                    models.DateTimeField(
                        auto_now=True,
                        db_column="update-at",
                        verbose_name="Fecha de Actualización",
                    ),
                ),
                (
                    "network_user",
                    models.ForeignKey(
                        blank=True,
                        db_column="network-user",
                        help_text="Usuario que escribe la nota",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.euser",
                        verbose_name="Usuario",
                    ),
                ),
                (
                    "id_ticket",
                    models.ForeignKey(
                        db_column="id-ticket",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tickets.ticket",
                        verbose_name="Ticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nota",
                "verbose_name_plural": "Notas",
                "db_table": "notes",
            },
        ),
    ]
