# Generated by Django 5.0.14 on 2025-12-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="icon",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Icono"
            ),
        ),
    ]
