# Generated by Django 5.0.14 on 2026-01-06 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ans",
            options={
                "ordering": ["id_ans"],
                "verbose_name": "ANS",
                "verbose_name_plural": "ANS",
            },
        ),
        migrations.AlterModelOptions(
            name="closingcode",
            options={
                "ordering": ["id_closing_code"],
                "verbose_name": "Código de Cierre",
                "verbose_name_plural": "Códigos de Cierre",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True,
                db_column="full-name",
                max_length=200,
                null=True,
                verbose_name="Nombre Completo",
            ),
        ),
        migrations.AlterField(
            model_name="euser",
            name="id_services",
            field=models.ForeignKey(
                blank=True,
                db_column="id-services",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.service",
                verbose_name="Servicio",
            ),
        ),
        migrations.AlterField(
            model_name="euser",
            name="user_client_name",
            field=models.ForeignKey(
                blank=True,
                db_column="user-client-name",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.client",
                verbose_name="Cliente",
            ),
        ),
    ]
