# Generated by Django 5.0.14 on 2026-02-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="is_completion",
            field=models.BooleanField(
                db_column="is-completion",
                default=False,
                help_text="Indica si este estado representa un cierre exitoso del ticket",
                verbose_name="Es Completado",
            ),
        ),
        migrations.AddField(
            model_name="status",
            name="ordering",
            field=models.IntegerField(
                db_column="ordering", null=True, verbose_name="Orden de los estados"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.CharField(
                blank=True,
                db_column="full-name",
                max_length=150,
                null=True,
                verbose_name="Nombre Completo",
            ),
        ),
        migrations.AlterField(
            model_name="ticket",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                db_column="assigned-to",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_tickets",
                to="tickets.euser",
                verbose_name="Asignado a",
            ),
        ),
        migrations.AlterField(
            model_name="workinghours",
            name="week_day",
            field=models.CharField(
                db_column="week-day",
                max_length=15,
                unique=True,
                verbose_name="Día de la Semana",
            ),
        ),
    ]
