# Generated by Django 5.0.14 on 2026-01-05 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_role_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportedtime",
            name="network_user",
            field=models.ForeignKey(
                blank=True,
                db_column="network-user",
                help_text="Usuario que reporta el tiempo",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.euser",
                verbose_name="Usuario de Red",
            ),
        ),
    ]
