# Generated by Django 5.0.14 on 2026-04-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tickets",
            "0002_status_is_completion_status_ordering_user_full_name_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="cumplimiento",
            field=models.BooleanField(
                blank=True,
                db_column="cumplimiento",
                help_text="Indica si el ticket cumple con las métricas establecidas",
                null=True,
                verbose_name="Cumplimiento",
            ),
        ),
    ]
