# Generated by Django 5.0.14 on 2026-01-07 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0003_reportedtime_network_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="network_user",
            field=models.ForeignKey(
                blank=True,
                db_column="network-user",
                help_text="Usuario que escribe la nota",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="tickets.euser",
                verbose_name="Usuario",
            ),
        ),
    ]
