# Generated by Django 5.0.14 on 2026-01-08 20:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0002_alter_ans_options_alter_closingcode_options_and_more"),
        ("tickets", "0004_note_network_user"),
    ]

    operations = []
