# Generated by Django 5.0.14 on 2026-01-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0004_note_network_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="is_backlog",
            field=models.BooleanField(
                db_column="is-backlog", default=False, verbose_name="Es Backlog"
            ),
        ),
    ]
