# Generated by Django 5.0.14 on 2026-01-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tickets", "0005_status_is_backlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingHours",
            fields=[
                (
                    "id_working_hours",
                    models.AutoField(
                        db_column="id-working-hours",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID de Horas Laborales",
                    ),
                ),
                (
                    "week_day",
                    models.CharField(
                        db_column="week-day",
                        max_length=15,
                        verbose_name="Día de la Semana",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        db_column="start-time", verbose_name="Hora de Inicio"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(db_column="end-time", verbose_name="Hora de Fin"),
                ),
            ],
            options={
                "verbose_name": "Horas Laborales",
                "verbose_name_plural": "Horas Laborales",
                "db_table": "working-hours",
            },
        ),
    ]
